/* Generated by AN DISI Unibo */ 
package it.unibo.ctxrbr
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.1.171", this, "standingbuffetservice.pl", "sysRules.pl"
	)
}

