version: '3'
services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi:2.0
    ## image: virtualrobotdisi:1.0
    ports:
      - 8090:8090
      - 8091:8091
  robot:
    image: docker.io/natbodocker/basicrobot21virtual:1.0
    ##image: basicrobot21virtual:1.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv

## ------------------------------------------------------------------------------------------------------------------------------
## docker-compose -f basicrobotVirtual.yaml up
## The first time after that, it could be necessary to add the file sceneConfig.js related to the simulated room in the WEnv:
## docker cp sceneConfig.js 6fc85fc771de:/home/node/WEnv/WebGLScene/sceneConfig.js
## where 6fc85fc771de is the CONTAINER ID, which can be found through a command that shows a list of containers:
## docker ps -a
## selecting the ID abount the containter of natbodocker/virtualrobotdisi:2.0.
## ------------------------------------------------------------------------------------------------------------------------------