/* Generated by AN DISI Unibo */ 
package it.unibo.rbrwalker

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Rbrwalker ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						itunibo.planner.plannerUtil.initAI(  )
						itunibo.planner.plannerUtil.loadRoomMap( "roomMap"  )
						itunibo.planner.plannerUtil.showMap(  )
						println("WALKER | STARTS...")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("WALKER | waits a goal...")
					}
					 transition(edgeName="t025",targetState="goToGoal",cond=whenRequest("setGoal"))
					transition(edgeName="t026",targetState="terminateWalker",cond=whenDispatch("end"))
				}	 
				state("goToGoal") { //this:State
					action { //it:State
						
									var X = ""
									var Y = ""
									var Dir = ""	
									var Ac = "empty"
									var CurDir = ""
									var CurPos : Pair<Int, Int> ?= null
						if( checkMsgContent( Term.createTerm("setGoal(X,Y,DIR)"), Term.createTerm("setGoal(X,Y,DIR)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												X = payloadArg(0)
												Y = payloadArg(1)
												Dir = payloadArg(2)
						}
						println("WALKER | received the goal ($X, $Y)...")
						itunibo.planner.plannerUtil.planForGoal( X, Y  )
							
									Ac = itunibo.planner.plannerUtil.getNextPlannedMove()
									while(Ac!="") {
						if(  Ac == "w"  
						 ){request("step", "step(647)" ,"basicrobot" )  
						}
						else
						 {forward("cmd", "cmd($Ac)" ,"basicrobot" ) 
						 }
						delay(1000) 
						itunibo.planner.plannerUtil.updateMap( Ac  )
						 
										Ac = itunibo.planner.plannerUtil.getNextPlannedMove()
									}
									
									//Turn the robot to be in front of the resource
									CurDir = itunibo.planner.plannerUtil.getDirection()
									while ( CurDir != Dir) {
						if(  (Dir == "leftDir" && CurDir == "upDir") || (Dir == "rightDir" && CurDir == "downDir") 
										   || (Dir == "upDir" && CurDir == "rightDir") || (Dir == "downDir" && CurDir == "leftDir")  
						 ){forward("cmd", "cmd(l)" ,"basicrobot" ) 
						itunibo.planner.plannerUtil.updateMap( "l"  )
						}
						else
						 {forward("cmd", "cmd(r)" ,"basicrobot" ) 
						 itunibo.planner.plannerUtil.updateMap( "r"  )
						 }
						delay(1000) 
						
										CurDir = itunibo.planner.plannerUtil.getDirection()
									}
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
						itunibo.planner.plannerUtil.updateMap( "h"  )
						delay(800) 
						 CurPos = itunibo.planner.plannerUtil.get_curPos()  
						itunibo.planner.plannerUtil.showMap(  )
						println("WALKER | arrived to the goal")
						answer("setGoal", "goalState", "goalState($CurPos)"   )  
						updateResourceRep( "$CurPos"  
						)
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("terminateWalker") { //this:State
					action { //it:State
						println("WALKER | terminate...")
						terminate(1)
					}
				}	 
			}
		}
}
