/* Generated by AN DISI Unibo */ 
package it.unibo.rbrwalker

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Rbrwalker ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						itunibo.planner.plannerUtil.initAI(  )
						itunibo.planner.plannerUtil.loadRoomMap( "roomMap"  )
						itunibo.planner.plannerUtil.showMap(  )
						println("WALKER | STARTS...")
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("WALKER | waits a goal...")
					}
					 transition(edgeName="t018",targetState="goToGoal",cond=whenRequest("setGoal"))
					transition(edgeName="t019",targetState="terminateWalker",cond=whenDispatch("end"))
				}	 
				state("goToGoal") { //this:State
					action { //it:State
						
									var X = ""
									var Y = ""	
									var Ac = "empty"
									var CurPos : Pair<Int, Int> ?= null
						if( checkMsgContent( Term.createTerm("setGoal(X,Y)"), Term.createTerm("setGoal(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												X = payloadArg(0)
												Y = payloadArg(1)
						}
						println("WALKER | received the goal ($X, $Y)...")
						itunibo.planner.plannerUtil.planForGoal( X, Y  )
							
									Ac = itunibo.planner.plannerUtil.getNextPlannedMove()
									while(Ac!="") {
						if(  Ac == "w"  
						 ){request("step", "step(770)" ,"basicrobot" )  
						}
						else
						 {forward("cmd", "cmd($Ac)" ,"basicrobot" ) 
						 }
						itunibo.planner.plannerUtil.updateMap( Ac  )
						 
										Ac = itunibo.planner.plannerUtil.getNextPlannedMove()
									}
									
									CurPos = itunibo.planner.plannerUtil.get_curPos() 
						itunibo.planner.plannerUtil.showMap(  )
						println("WALKER | arrived to the goal")
						answer("setGoal", "goalState", "goalState($CurPos)"   )  
						updateResourceRep( "$CurPos"  
						)
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("terminateWalker") { //this:State
					action { //it:State
						println("WALKER | terminate...")
						terminate(1)
					}
				}	 
			}
		}
}
