/* Generated by AN DISI Unibo */ 
package it.unibo.fridge

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Fridge ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("FRIDGE | STARTS and it's embedded with the proper set of food")
						solve("consult('FridgeInit.pl')","") //set resVar	
						delay(300) 
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						println("FRIDGE | is waiting for a command...")
					}
					 transition(edgeName="t114",targetState="changeFood",cond=whenDispatch("add"))
					transition(edgeName="t115",targetState="changeFood",cond=whenDispatch("remove"))
					transition(edgeName="t116",targetState="answerFood",cond=whenDispatch("askFood"))
					transition(edgeName="t117",targetState="exposeState",cond=whenDispatch("consult"))
				}	 
				state("changeFood") { //this:State
					action { //it:State
						 var Food_Code = ""   
						if( checkMsgContent( Term.createTerm("add(X)"), Term.createTerm("add(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Food_Code = payloadArg(0) 
								println("FRIDGE | add $Food_Code...")
						}
						if( checkMsgContent( Term.createTerm("remove(X)"), Term.createTerm("remove(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Food_Code = payloadArg(0) 
								println("FRIDGE | remove $Food_Code...")
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("answerFood") { //this:State
					action { //it:State
						 var Food_Code = "" 
								   var FoodPresence = false
						if( checkMsgContent( Term.createTerm("askFood(FOODE_CODE)"), Term.createTerm("askFood(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Food_Code = payloadArg(0)  
						}
						println("FRIDGE | searching Food_Code $Food_Code...")
						updateResourceRep("FoodPresence:$FoodPresence" 
						)
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("exposeState") { //this:State
					action { //it:State
						var State = "a" 
						println("FRIDGE | exposed content to maitre")
						updateResourceRep("State:$State" 
						)
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
